name: Azure FastAPI Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      working-directory: ./Buddy_Backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Upload to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: buddy-backend-fastapi  # Replace with your Azure app name
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./Buddy_Backend
